# Generated by Django 3.2 on 2022-06-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_data',
            new_name='doctors',
        ),
    ]
